### ISSUE TITLE
About Solutiions' validity

### ISSUE THREAD

**Issue by MrBlack0220** [hendrycks/apps#26]
Thanks for creating this amazing datasets.
I want to ask if any solution in Solutions.json is strictly correct (can pass all unit tests in input_output.json )?
Do you check it?
If not，how do you ensure the correctness of the solution?
Thanks!

**Comment by xksteven** [comment]
All the solutions were pulled from websites with thousands of users. The answers are all valid as they've been checked by the writers and users. The solutions are valid in so far as they are able to produce the correct answers given the corresponding inputs. We worked to ensure that all the ones we gathered are valid and match that description. Beyond that we also excluded solutions which took to long to compute. For more details feel free to read the corresponding paper as to more specifics about the data collection process. 

Hope that answers your question.

**Comment by nicoladainese96** [comment]
Hi, I'm encountering a problem in evaluating the solutions. For a preliminary pipeline in which I want to process all APPS benchmark with an LLM, I'm just taking one random solution among the available ones if present, otherwise using an empty solution. For the competition problems, test split, out of 1000 problems, only 311 have solutions, so in my case I should get a strict accuracy of 31.1% given that the solutions for the other 689 are left empty. However, I get the following results:

Test Case Average (average accuracy over problems) = 0.27318586602648753
Strict Accuracy (all test cases passed / total problems) = 0.263

Here's a screenshot of the last part of the evaluation script. Is it possible that certain solutions are only partially correct?

![Screenshot 2024-04-29 at 14 35 30](https://github.com/hendrycks/apps/assets/43784881/fb1857d8-ad39-4903-bc85-7735ad359c03)
